# Generated by Django 4.1.7 on 2023-12-14 16:37

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('backup_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_joined', models.DateTimeField(default=datetime.datetime(2023, 12, 14, 16, 37, 40, 859044))),
            ],
        ),
    ]
