# Generated by Django 4.1.7 on 2023-12-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_page_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='name',
            new_name='title',
        ),
    ]
