# Generated by Django 4.1.7 on 2023-12-14 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_tag_page_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='info.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='pages',
            field=models.ManyToManyField(blank=True, null=True, to='info.page'),
        ),
    ]
