# Generated by Django 4.1.7 on 2023-12-14 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0006_alter_page_tags_alter_tag_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='page', to='info.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='pages',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='info.page'),
        ),
    ]
